### ISSUE TITLE
错误处理

### ISSUE THREAD

**Issue by misaka10055** [exxhentai/flask#11]
@r1235613  对于错误处理，例如找不到资源时返回 404 的时候，你是怎么实现的？

我目前暂且是用的 Flask 的 abort，不过你有没有什么更好的方案？

**Comment by r1235613** [comment]
找不到資源不應該回傳404，端點本身是存在的，所以匹配不到資源應該是回傳200，空陣列
我個人寫錯誤都是直接`return jsonify({"msg": "好像有啥炸掉了"}), 500`

**Comment by misaka10055** [comment]
OK。那我也这么处理以保证一致。
