### ISSUE TITLE
使用者互動資料

### ISSUE THREAD

**Issue by r1235613** [exxhentai/flask#6]
目前經由上傳者以外之使用者提供的資料，且會變動的有：

- 分數

- 收藏數

- 標籤權重

這些資料要怎麼辦，像是標籤權重與分數是網友投票結果，這部分怎麼處理，設置一個初始值嗎？
以分數為例，因為沒有評分網友個別的評價，所以如果再多一個人打5星，我不知道要如何變更分數。
至於蒐藏數我覺得可以歸零，反正大家的蒐藏都炸了wwww

**Comment by misaka10055** [comment]
我感觉目前只能设置一个初始值了，这部分数据应该是找不回来了。

我的建议是rating 就假定每个work都有n （大概100差不多？）个人评过分，然后每次评分再加权算。

收藏就归零吧（。

标签权重我感觉在用的时候并不是特别重要，这个也规定个初始值好了？

**Comment by Minasemaoking** [comment]
我認為分數與收藏數一樣一併歸零即可，讓使用者自行評分這項數據才有意義。
當然如果有原始評分資料人數之類的，算給他初始值也無妨。
但是如果沒有，還是給舊作分數初始值，會與往後的新上傳的作品分數統計方式不一致，導致在使用者在使用上的混亂。

假設只有一個人打5*這個問題，可以參考EH原有的分數評級方式，我認為是挺不錯的
他除了顯示目前評級分數，還可以顯示投票人數當作參考的可信度

標籤權重這部分我覺得也是初始值就好了，假設能有更多的資料，(例如:標籤投票人數，標籤累計加權分數)，我們才有辦法對舊作品標籤做下一步的改善。
