### ISSUE TITLE
API 是否要与 E-Hentai API 一致

### ISSUE THREAD

**Issue by misaka10055** [exxhentai/flask#7]
如果API 的格式与 e-hentai 一致的话，各个客户端的适配会容易许多（只用改一下Base URL就可以了）。

但是 E-hentai的 API 我感觉不是特别方便使用，比如请求Gallery的详情不仅要提供gid 还要提供token，还有详情API没有收藏数等信息，如果我们改进一下应该会更加客户端友好。

**Comment by r1235613** [comment]
難用，但是我認為可以提供向下支援（多開一個的意思

**Comment by GooeyNyan** [comment]
可以 /api/v1 兼容 EH API，/api/v2 写新的 API

**Comment by misaka10055** [comment]
OK 那就做一个新API，同时提供一个旧版API供快速适配。
