### ISSUE TITLE
儲存格式確認

### ISSUE THREAD

**Issue by r1235613** [exxhentai/flask#8]
我打算這樣存東西，以下是說明：

- title：必定會有，字串
- japan_title：可能會有，若無則為null
- catagroy：必定會有
- rating：必定會有值，前為分數，後為透明度
- ipfs_url：目前都為null，等待go小組添加
- tags：key為標簽名，value為分數，舊的畫廊預設為100（實線）與10（虛線），但是不能更改
- uploader：若為匯入資料，會以`ex_`開頭，ex前綴為系統保留
- upload_time：為時間，UTC+0的unix時戳
- ex：若是來自ex的資料，會有舊的畫廊資訊，若無會是null

```javascript
{
  "title": "It has been ruined Home ten years later when I made passes at the boy of the friend of the pretty son",
  "japan_title": "(C71) [ありさんアンテナ (小蟻)] Eat The Rich! (スカッとゴルフ パンヤ)",
  "category": "Artist CG",
  "rating": [4.57, 100],
  "ipfs_url": null,
  "tags": {
    "language": {
      "english": 31
    },
    "character": {
      "tomoko kuroki": 24
    },
    "femail": {
      "beauty mark": 26,
      "bikini": 23,
      "dark skin": -2,
      "anal": 999
    },
    "male": {
      "dark skin": 98
    },
    "group": {
      "ikigire shoukai": 26
    },
    "artist": {
      "gabe": 25
    },
    "misc": {
      "mosaic censorship": 1
    }
  },
  "uploader": "ex_SnowTig3r",
  "upload_time": 1564543342 ,
  "file_count": 37,
  "ex": {
    "page_link": "https://exhentai.org/g/1452597/fbbca79ca2/",
    "gid": "9",
    "token": "e56264c60c"
  }
}
```

**Comment by misaka10055** [comment]
我觉得OK。这个数据还是挺全的。

不过这里的gid 是nullable 的？如果gid 不存在的话，有什么Unique ID可以用来查找特定的一部作品吗？在详情页面，如果要评论/打分的话，数据得和某一个特定作品关联。

或许MongoDB的 Hash ID可以用作唯一ID？

**Comment by GooeyNyan** [comment]
首先 `uploader` 只是存 uploader 的 id 吧，user <—> gallery 一对多的关系，在另外的 user 表维护。

然后 tags，再商榷吧，这样子感觉不方便搜索

**Comment by r1235613** [comment]
@GooeyNyan 您的論述是基於非關連式資料庫的評價嗎？

**Comment by GooeyNyan** [comment]
> @GooeyNyan 您的論述是基於非關連式資料庫的評價嗎？

你说得有道理，我确实是基于关系型数据库评价的。

但是只存 username，怎么关联上用户别的信息呢。相比于在 name 上建索引，还是倾向于在 id 上建索引的感觉。

**Comment by r1235613** [comment]
@GooeyNyan 若是舊的畫廊，實際上能用的就只有名字了，新的上傳才會有使用者
另外，若是再次上傳，上傳者要是原ex的帳號，還是補檔的人？

**Comment by r1235613** [comment]
若僅剩下元資料，則上傳者為空，原ex上傳者移至ex資料區段？
若有補檔，則補檔者為上傳者，用mongo db的id存。
```javascript
{
  "title": "It has been ruined Home ten years later when I made passes at the boy of the friend of the pretty son",
  "japan_title": "(C71) [ありさんアンテナ (小蟻)] Eat The Rich! (スカッとゴルフ パンヤ)",
  "category": "Artist CG",
  "rating": [4.57, 100],
  "ipfs_url": null,
  "thumbnail ": null,
  "tags": {
    "language": {
      "english": 31
    },
    "character": {
      "tomoko kuroki": 24
    },
    "femail": {
      "beauty mark": 26,
      "bikini": 23,
      "dark skin": -2,
      "anal": 999
    },
    "male": {
      "dark skin": 98
    },
    "group": {
      "ikigire shoukai": 26
    },
    "artist": {
      "gabe": 25
    },
    "misc": {
      "mosaic censorship": 1
    }
  },
  "uploader": null,
  "upload_time": null,
  "file_count": 37,
  "ex": {
    "page_link": "https://exhentai.org/g/1452597/fbbca79ca2/",
    "gid": "9",
    "upload_time": 1564543342 ,
    "token": "e56264c60c"
  }
}
```

**Comment by misaka10055** [comment]
我感觉我们总归还是要维护一张user表的。毕竟以后会有账户系统

**Comment by r1235613** [comment]
Yes，那部分開一個新issue來討論吧，不過也可能帳戶系統由go他們那邊來維護
因為若是我們開帳戶系統的話，必然要開類似oauth的驗證API，總之還沒討論出結果
https://github.com/exxhentai/rehentai/issues/3

**Comment by r1235613** [comment]
不過也可能帳戶系統由go他們那邊來維護

**Comment by Minasemaoking** [comment]
以mongoDB來說，建index 用id做關聯是最理想的情況，與其控制name是不是unique，我認為用id 會比較安全，再討論之前，我先暫時將兩個表先命名，方便後續討論。

第一，如樓上所說，我認為可以直接先分別建立 galleryInfo 與 userInfo的 collection
並在galleryInfo 中新增欄位 uploaderId
 
在這裡用userInfo 中 name的欄位去找 galleryInfo 的uploader， 塞入對應的userId 到 uploaderId中
若是有找不到對應的userName，我們可以給他一個預設值
可能是unknown 或是 ehPanda之類的，也可以當一個梗。
之後我們都用這個userId/uploaderId 去 做 mapping
 
用id 做關聯的用意是在未來要更動user 資訊時，比較不會那麼麻煩
否則用name做關聯以後如果要更動會是很麻煩的事情。

另外在db內建議還是給空值，不要是null
如果user的欄位出來了，兩張表的架構到時候可以再討論

**Comment by r1235613** [comment]
@Minasemaoking 能說明空值優於null的原因嗎？
如過是前端的需要，我想我們能夠於提供API時轉為空字串。

**Comment by Minasemaoking** [comment]
@r1235613
在mongoDB中，如果null不是存字串，他會直接不存這個欄位，在管理DB時不容易看出來哪個資料欄位少了。

二來覺得在嚴謹的情況下丟null其實不太好，在後端接到值時還需要先寫判斷是不是null，如果一開始預設空值，就不用擔心接到null產生不必要的bug，再來在意義上，目前空的欄位並不完全算是一個未知欄

雖然對後端來說，丟兩者其實也都是可以做的。

**Comment by r1235613** [comment]
@Minasemaoking 瞭解，學到一課了，的確是存空字串較好處理。
那這格式就這樣定了哦？

**Comment by GooeyNyan** [comment]
> @Minasemaoking 瞭解，學到一課了，的確是存空字串較好處理。
> 那這格式就這樣定了哦？

想起来还差 thumbnail 缩略图字段

**Comment by r1235613** [comment]
@GooeyNyan  一樣是星際連結嗎？

**Comment by r1235613** [comment]
@Minasemaoking 我剛試了一下，MongoDB是可以區分未定義與null的，管理上不會有問題；另外在我的理解null是空的意思……不知道這樣理解對不對。
不過話是這樣說，但還是以照前端易作業的形式處理吧

**Comment by GooeyNyan** [comment]
> @GooeyNyan 一樣是星際連結嗎？

是，我前两天有把一部分上传 ipfs，不过想想不如等 metadata 完全定好了我再直接 update，就没继续跑了。

**Comment by Minasemaoking** [comment]
@r1235613 如果是字串包null 是可以的存的，因為他就只是個字串，但如果直接set 這個欄位是 null
就不會存進去，你測試時是直接塞null嗎? 還是塞 一個String是"null"

在mongoDB中，任何沒有預設值的欄位都會是null，他沒有值，但不是一個空值
例如
List<ObjectId> myList = null;
與
List<ObjectId> mySecondList = new ArryaList<ObjectId>();
兩個陣列存進去後，在mongoDB中，你會看不到myList，但是丟回前端時，他會這樣顯示
{"myList":null} ，意思是這個欄位沒有值

而mySecondList在DB中會顯示 {"mySecondList":[]}
丟回前端時也是 {"mySecondList":[]} 這個我會稱他為空值

**Comment by r1235613** [comment]
我是這樣存的，我認為他們是可以區分的，亦即有未定義、null、有值這幾種狀態
![圖片](https://user-images.githubusercontent.com/14368787/62292973-832d5a80-b4a2-11e9-8bc2-434b61d011c2.png)
![圖片](https://user-images.githubusercontent.com/14368787/62293010-9a6c4800-b4a2-11e9-84ad-f6f7bef6f443.png)
然後出現了不可預期的錯誤……，我想搜尋test是null且不是未定義的
![圖片](https://user-images.githubusercontent.com/14368787/62293654-0a2f0280-b4a4-11e9-892b-6025825d7e0a.png)

**Comment by Minasemaoking** [comment]
我看了一下mongoDB的doc，這應該是我們想知道的
這是直接在DB insert一個test欄位是null嘛?
http://www.mongoing.com/docs/tutorial/query-for-null-fields.html

**Comment by r1235613** [comment]
這真是……總之我用空字串了

**Comment by r1235613** [comment]
因為Tag有不合法的字元`.`，所以我改了一下格式
```
"tags": {
    "language": [
      ["english", 31]
    ],
    "character": [
      ["tomoko kuroki", 24]
    ],
    "femail": [
      ["beauty mark", 26],
      ["bikini", 23],
      ["dark skin", -2],
      ["anal", 999]
    ],
    "male": [
      ["dark skin", 98]
    ],
    "group": [
      ["ikigire shoukai", 26]
    ],
    "artist": [
      ["gabe", 25]
    ],
    "misc": [
      ["mosaic censorship", 1]
    ]
  }
```

**Comment by r1235613** [comment]
整理好了，不過原站也復活了……
https://send.firefox.com/download/be6762198b2a8492/#X3LLVyTOMYX83m_zE5NYEA
